version: "3.8"

services:
  build:
    image: ghcr.io/cpdevtools/docker-dotnet-images/dotnet-sdk:7.0.0-dev.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "${PROJECTS}/lib-dotnet-webservices:/src"

    working_dir: /src/projects/TestProject
    command: "pnpm run docker-build"

  start:
    image: ghcr.io/cpdevtools/docker-dotnet-images/dotnet-sdk:7.0.0-dev.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "${PROJECTS}/lib-dotnet-webservices:/src"

    working_dir: /src/projects/TestProject
    command: "pnpm run docker-start"
