name: "Publish npm module"
description: "Publish the npm module"

inputs:
  packPath:
    description: "The path to the directory containing the nuget packages"
    required: false
    default: ".pack"
  githubToken:
    description: "Github Token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.packPath }}
      run: |
        dotnet nuget push **/*.nupkg
