name: "Publish npm module"
description: "Publish the npm module"

inputs:
  packPath:
    description: "The path to the directory containing the nuget packages"
    required: false
    default: ".pack"
  githubToken:
    description: "Github Token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v3.0.3
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.githubToken }}
      with:
        dotnet-version: "${{ inputs.dotnetVersion }}"
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - shell: bash
      working-directory: ${{ inputs.packPath }}
      run: |
        dotnet nuget push **/*.nupkg
