name: Push - Test

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!release/*"

jobs:
  check_builds:
    name: Project builds successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Install Node & Dependencies
        uses: ./.github/actions/setup-node

      - name: Build
        uses: ./.github/actions/build

      - name: Run Tests
        uses: ./.github/actions/test
