name: OnPush - Create PR

on:
  push:
    branches:
      - "main"
      - "master"
      - "v/*"

jobs:
  create_pr:
    name: Create a Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - uses: ./.github/actions/create-pull-request
