name: OnPush - Create Release

on:
  push:
    branches:
      - "release/*"

jobs:
  setup:
    name: Setup Release Information
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      isPrerelease: ${{ steps.version.outputs.isPrerelease }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      - name: Check Version
        id: version
        uses: ./.github/actions/check-version

  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Setup Node & Dependencies
        uses: ./.github/actions/setup-node

      - name: Setup Dotnet
        uses: ./.github/actions/setup-dotnet

      - name: Set Version
        uses: ./.github/actions/set-version
        with:
          version: ${{ needs.setup.outputs.version }}

      - name: Pack
        uses: ./.github/actions/pack

      - name: Publish
        uses: ./.github/actions/publish-dotnet-package

  create-release:
    name: Create Github release and tags
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Create Release
        uses: ./.github/actions/create-release
